apiVersion: apps/v1
kind: Deployment
metadata:
    name: exames-front-deployment
    labels:
        app: exames-front
spec:
    replicas: 2
    selector:
        matchLabels:
            app: exames-front
    template:
        metadata:
            labels:
                app: exames-front
        spec:
            containers:
                - name: exames-front
                  image: kelvinsouza258/exames-front:v1.0
                  ports:
                      - containerPort: 3000
                  env:
                      - name: API_URL
                        valueFrom:
                            configMapKeyRef:
                                name: exames-config
                                key: api-url

---
apiVersion: v1
kind: Service
metadata:
    name: exames-front-service
    labels:
        app: exames-front
spec:
    type: NodePort
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 30100
    selector:
        app: exames-front
